services:
  postgres:
    image: postgres:15-alpine
    container_name: nexhire-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nexhire
    ports:
      - "5433:5432"
    volumes:
      - nexhire-db-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  nexhire-db-data:
